### ISSUE TITLE
storiesファイル作成時、一部コンポーネントがエラー状態になる

### ISSUE THREAD

**Issue by okky-hi** [ms2sato/starter-gatsby-firebase-site#11]
コンポーネントからstoriesファイルを作成した後にStorybookを立ち上げると、画面は表示されるが作成したコンポーネントをクリックするとエラーが表示される

### エラー内容の要約（chatGPT）
- エラーの原因
  - useFormContext() が null を返しているため、useFormField 関数で getFieldState などの値を取得できずエラーが発生しています。
- 主な要因
  - useFormContext() は FormProvider コンテキストが設定されている必要がありますが、Storybook の環境で FormProvider が適切に適用されていないため、useFormContext() が null を返しています。
- 解決のヒント
  - Storybook で FormProvider をデコレーターなどを使って適切に設定することで、useFormContext() が null にならないようにする必要があります。

### 対象ファイル
- site/src/components/Form/Label/Label.stories.ts
- site/src/components/Form/FormMessage/FormMessage.stories.tsx

### 参考になりそうなドキュメント
- https://zenn.dev/cykinso/articles/152abb5bf9cd69
- https://gist.github.com/shumbo/3bbb8a2dea5ea0a90ecf0b7c103783e8

### エラー原文
```
Cannot destructure property 'getFieldState' of '(0 , react_hook_form__WEBPACK_IMPORTED_MODULE_2__.useFormContext)(...)' as it is null.
The component failed to render properly, likely due to a configuration issue in Storybook. Here are some common causes and how you can address them:

Missing Context/Providers: You can use decorators to supply specific contexts or providers, which are sometimes necessary for components to render correctly. For detailed instructions on using decorators, please visit the Decorators documentation.
Misconfigured Webpack or Vite: Verify that Storybook picks up all necessary settings for loaders, plugins, and other relevant parameters. You can find step-by-step guides for configuring Webpack or Vite with Storybook.
Missing Environment Variables: Your Storybook may require specific environment variables to function as intended. You can set up custom environment variables as outlined in the Environment Variables documentation.
TypeError: Cannot destructure property 'getFieldState' of '(0 , react_hook_form__WEBPACK_IMPORTED_MODULE_2__.useFormContext)(...)' as it is null.
    at useFormField (http://localhost:6006/components-Form-FormMessage-FormMessage-stories.iframe.bundle.js:391:13)
    at http://localhost:6006/components-Form-FormMessage-FormMessage-stories.iframe.bundle.js:307:103
    at renderWithHooks (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_index_mjs-node_modules_storybook_addon-esse-e70b4a.iframe.bundle.js:36555:157)
    at updateForwardRef (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_index_mjs-node_modules_storybook_addon-esse-e70b4a.iframe.bundle.js:36980:200)
    at beginWork (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_index_mjs-node_modules_storybook_addon-esse-e70b4a.iframe.bundle.js:37468:1559)
    at beginWork$1 (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_index_mjs-node_modules_storybook_addon-esse-e70b4a.iframe.bundle.js:38524:93)
    at performUnitOfWork (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_index_mjs-node_modules_storybook_addon-esse-e70b4a.iframe.bundle.js:38350:270)
    at workLoopSync (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_index_mjs-node_modules_storybook_addon-esse-e70b4a.iframe.bundle.js:38336:30)
    at renderRootSync (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_index_mjs-node_modules_storybook_addon-esse-e70b4a.iframe.bundle.js:38332:159)
    at recoverFromConcurrentError (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_index_mjs-node_modules_storybook_addon-esse-e70b4a.iframe.bundle.js:38211:170)
```

**Comment by ms2sato** [comment]
ChatGPTのアドバイス通りと思いました

**Comment by okky-hi** [comment]
withRHFでStorybookFormProviderを呼び出し、RHFが必要なパーツを自動でFormProviderで包む。
対象ファイル2つともエラーなくstoriesの作成に成功したのでclose
